### PR TITLE
Rename koiki.models to koiki.resources

### LINKED ISSUE #91: Rename models on koiki to resources

### PR DESCRIPTION
**Pull request by daniquilez**
Fix #91

### CODE REVIEW

**Comment by daniquilez** [comment]
While doing the task I've noticed it would be also interesting to rename koiki.woocommerce.models to koiki.woocommerce.resources

What do you think?

**Comment by daniquilez** [comment]
While doing the task I've noticed we could also rename koiki.woocommerce.models into koiki.woocommerce.resources
What do you think?

**Comment by sauloperez** [comment]
yes, the initial idea was to do both.

**Comment by daniquilez** [comment]
Ok. Changes made. You can review and merge if it's ok. Thanks!

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
Thoughts @numeropi ?

**Pull request merged**
